[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
